name: AutoVehicles
version: '1.3.0'
main: me.tisleo.autominecart.AutoMinecart
api-version: 1.18
authors: [ TisLeo ]
description: A useful plugin that mimics Terraria minecarts and adds custom boats

commands:
  togglecart:
    description: Toggle AutoMinecart on or off for yourself
    usage: /togglecart
  toggleboat:
    description: Toggle AutoBoat on or off for yourself
    usage: /toggleboat
  toggleparticles:
    description: Toggle vehicle particle effects on or off for yourself
    usage: /toggleparticles

permissions:
  autominecart.use:
    description: Allows a user to use this plugin
    default: op
  autovehicles.particles:
    description: Allows a user to see particle effects on their vehicles
    default: op
  autovehicles.particles.toggle:
    description: Allows a user to toggle their vehicle particle effects
    default: op