name: AutoVehicles2
version: '2.1.0'
main: me.onecraft.autovehicles2.AutoVehicles2
api-version: 1.21
authors: [ OneCraft ]
description: A powerful plugin that enhances vehicles with automatic spawning and reliable cleanup.

commands:
  togglecart:
    description: Toggle AutoMinecart on or off for yourself
    usage: /togglecart
  toggleboat:
    description: Toggle AutoBoat on or off for yourself
    usage: /toggleboat
  toggleparticles:
    description: Toggle vehicle particle effects on or off for yourself
    usage: /toggleparticles

permissions:
  autovehicles2.use:
    description: Allows a user to use this plugin
    default: op
  autovehicles2.particles:
    description: Allows a user to see particle effects on their vehicles
    default: op
  autovehicles2.particles.environment:
    description: Allows a user to see environmental and biome-specific particle effects
    default: op
  autovehicles2.particles.toggle:
    description: Allows a user to toggle their vehicle particle effects
    default: op